apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: ecom-v1
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: paymentservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
          env:
            - name: SERVER_PORT
              value: "5002"
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: DB_PASS
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: EUREKA_SERVER
            - name: JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: JWT_ISSUER_URI
            - name: RAZORPAY_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: RAZORPAY_KEY_ID
            - name: RAZORPAY_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: RAZORPAY_KEY_SECRET
            - name: RAZORPAY_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: RAZORPAY_WEBHOOK_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: ecom-v1
spec:
  selector:
    app: paymentservice
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP 