apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice
  namespace: ecom-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notificationservice
  template:
    metadata:
      labels:
        app: notificationservice
    spec:
      containers:
        - name: notificationservice
          image: notificationservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: SERVER_PORT
              value: "5001"
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: SMTP_PORT
            - name: SMTP_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: SMTP_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: SMTP_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: KAFKA_BOOTSTRAP_SERVERS
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: notificationservice
  namespace: ecom-v1
spec:
  selector:
    app: notificationservice
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP 