apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: ecom-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: cartservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7001
          env:
            - name: PORT
              value: "7001"
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: EUREKA_SERVER
            - name: MONGO_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: MONGO_DB_URL
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: MONGO_DB_NAME
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: REDIS_URL
            - name: JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: JWT_ISSUER_URI
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: ORDER_SERVICE_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: ecom-v1
spec:
  selector:
    app: cartservice
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 7001
  type: ClusterIP 