apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauthserver
  namespace: ecom-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauthserver
  template:
    metadata:
      labels:
        app: oauthserver
    spec:
      containers:
        - name: oauthserver
          image: oauthserver:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9001
          env:
            - name: SERVER_PORT
              value: "9001"
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: DB_PASS
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: EUREKA_SERVER
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: ADMIN_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: oauthserver
  namespace: ecom-v1
spec:
  selector:
    app: oauthserver
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP 