apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
  namespace: ecom-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: orderservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6000
          env:
            - name: SERVER_PORT
              value: "6000"
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: DB_PASS
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: EUREKA_SERVER
            - name: JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: JWT_ISSUER_URI
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: CART_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: CART_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: PAYMENT_SERVICE_URL
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: USER_SERVICE_URL
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: PRODUCT_SERVICE_URL
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
  namespace: ecom-v1
spec:
  selector:
    app: orderservice
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: ClusterIP 