apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
template:
  metadata:
    labels:
      app: grafana
  spec:
    containers:
      - name: grafana
        image: grafana/grafana:latest
